alaya/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('pacientes.urls', namespace="paciente")),
    url(r'^', include('fichaClinica.urls', namespace="fichaClinica")),
]

fichaClinica/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .models import *
from .views import *
from .models import *

urlpatterns = [
    # ficha clinica
    url(r'^ficha_clinica/listar$', FichaClinicaList.as_view(), name='ficha_clinica_list'),
    url(r'^ficha_clinica/crear$', FichaClinicaCreate.as_view(), name='ficha_clinica_crear'),
    url(r'^ficha_clinica/editar$', FichaClinicaUpdate.as_view(), name='ficha_clinica_editar'),
    url(r'^ficha_clinica/eliminar$', FichaClinicaDelete.as_view(), name='ficha_clinica_eliminar'),
]

pacientes/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .models import *
from .views import *
from .models import *

urlpatterns = [
    # pacientes
    url(r'^paciente/listar$', PacienteList.as_view(), name='paciente_list'),
    url(r'^paciente/crear$', PacienteCreate.as_view(), name='paciente_crear'),
    url(r'^paciente/editar$', PacienteUpdate.as_view(), name='paciente_editar'),
    url(r'^paciente/eliminar$', PacienteDelete.as_view(), name='paciente_eliminar'),
]

fichaClinica/models.py
from django.db import models

# Create your models here.
class FichaClinica(models.Model):
	enfermedades = models.CharField(max_length=255, null=False)
	tratamiento = models.CharField(max_length=255, null=False)
	fecha_enfermedad = models.DateTimeField(auto_now_add=False, auto_now=False)
	fecha_termino_tratamiento = models.DateTimeField(auto_now_add=False, auto_now=False)
	resultado_tratamiento = models.CharField(max_length=255, null=False)

def __str__(self):
	return self.enfermedades

pacientes/models.py
from django.db import models
from fichaClinica.models import FichaClinica

# Create your models here.
class Pacientes(models.Model):
	nombre = models.CharField(max_length=255, null=False)
	rut = models.CharField(max_length=10, null=False)
	fecha_nacimiento = models.DateTimeField(auto_now_add=False, auto_now=False)
	fecha_ingreso = models.DateTimeField(auto_now_add=False, auto_now=False)
	ficha_clinica = models.ForeignKey(FichaClinica, null=True, blank=True, on_delete=models.CASCADE)

def __str__(self):
    return self.nombre

fichaClinica/forms.py
from django import forms

from .models import FichaClinica


class FichaClinicaForm(forms.ModelForm):
    class Meta:
        model = FichaClinica

        fields = [
            'enfermedades',
            'tratamiento',
            'fecha_enfermedad',
            'fecha_termino_tratamiento',
            'resultado_tratamiento',
        ]

        labels = {
            'enfermedades': 'Enfermedades',
            'tratamiento': 'Tratamiento',
            'fecha_enfermedad': 'Fecha inicio enfermedad',
            'fecha_termino_tratamiento': 'Fecha termino tratamiento',
            'resultado_tratamiento': 'resultado_tratamiento',
        }

        widgets = {
            'enfermedades': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese enfermedad...'}),
            'tratamiento': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese tratamiento...'}),
            'fecha_enfermedad': forms.SelectDateWidget(),
            'fecha_termino_tratamiento': forms.SelectDateWidget(),
            'resultado_tratamiento': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese resultado tratamiento...'}),
        }

pacientes/forms.py
from django import forms

from .models import Pacientes


class PacientesForm(forms.ModelForm):
    class Meta:
        model = Pacientes

        fields = [
            'nombre',
            'rut',
            'fecha_nacimiento',
            'fecha_ingreso',
            'ficha_clinica',
        ]

        labels = {
            'nombre': 'Nombre',
            'rut': 'Rut',
            'fecha_nacimiento': 'Fecha de nacimiento',
            'fecha_ingreso': 'Fecha de ingreso',
            'ficha_clinica': 'Ficha clinica',
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese nombre paciente...'}),
            'rut': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese rut paciente...'}),
            'fecha_nacimiento': forms.SelectDateWidget(),
            'fecha_ingreso': forms.SelectDateWidget(),
            'ficha_clinica': forms.Select(attrs={'class': 'form-control'}),
        }

fichaClinica/views.py
from django.shortcuts import render
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from .forms import *
from .models import *
from .urls import *
from django.views.generic import View
# Create your views here.

class FichaClinicaList(ListView):
    model = FichaClinica
    template_name = 'ficha_clinica_list.html'

class FichaClinicaCreate(CreateView):
    model = FichaClinica
    form_class = FichaClinicaForm
    template_name = 'ficha_clinica_create.html'
    success_url = reverse_lazy('fichaClinica:ficha_clinica_list')
    success_message = 'Ficha creada'

class FichaClinicaUpdate(UpdateView):
    model = FichaClinica
    form_class = FichaClinicaForm
    template_name = 'ficha_clinica_update.html'
    success_url = reverse_lazy('fichaClinica:ficha_clinica_list')


class FichaClinicaDelete(DeleteView):
    model = FichaClinica
    template_name = 'ficha_clinica_delete.html'
    success_url = reverse_lazy('fichaClinica:ficha_clinica_listar')

pacientes/views.py
from django.shortcuts import render
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from .forms import *
from .models import *
from .urls import *
from django.views.generic import View
# Create your views here.

class PacienteList(ListView):
    model = Pacientes
    template_name = 'paciente_list.html'

class PacienteCreate(CreateView):
    model = Pacientes
    form_class = PacientesForm
    template_name = 'paciente_create.html'
    success_url = reverse_lazy('paciente:paciente_list')
    success_message = 'Paciente creado'

class PacienteUpdate(UpdateView):
    model = Pacientes
    form_class = PacientesForm
    template_name = 'paciente_update.html'
    success_url = reverse_lazy('paciente:paciente_list')


class PacienteDelete(DeleteView):
    model = Pacientes
    template_name = 'paciente_delete.html'
    success_url = reverse_lazy('paciente:paciente_listar')

fichaClinica/templates/ficha_clinica_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sistema | Ficha Clinica</title>
</head>
<body>
    {% extends 'adminlte/base.html'%}

    {%block content%}
    <div class="col-sm-12">
        <h1>Ficha Clinica</h1>
        <hr>
        <form method="POST" action="">
            {% csrf_token%}
            {{form.as_p}}
            <input type='submit' class="btn btn-primary" value='Guardar Registro'>
        </form>
    </div>
</body>
</html>
{%endblock%}

fichaClinica/templates/ficha_clinica_delete.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Sistema | Eliminar Ficha Clinica</title>
  </head>
{% extends 'adminlte/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar la ficha clinica "{{ficha_clinica_list.id}}" ?</h3>
    <button class = "btn btn-danger" type="submit">Si, eliminar</button>
    <a class = "btn btn-default" href="{% url 'fichaClinica:ficha_clinica_list' %}">Cancelar</a>

</form>
</html>
{% endblock %}

fichaClinica/templates/ficha_clinica_list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema | Listar Fichas Clinicas</title>
</head>
{% extends 'adminlte/base.html' %}
{% block content %}
<div id="" class="gray-bg"><br>
	{% if object_list %}
	<div class="table-responsive"/>
	<h1>LISTA DE FICHA CLINICAS</h1>
	<hr>
	<table class="table table-bordered">
		<thead>
			<tr>
				<td>Codigo</td>
				<td>Enfemedades</td>
				<td>Tratamiento</td>
				<td>Fecha de enfermedad</td>
				<td>Fecha termino tratamiento</td>
				<td>Resultado tratamiento</td>
			</tr>
		</thead>
		<tbody>
			{% for ficha_clinica in object_list %}
			<tr>
				<td>{{ficha_clinica_list.codigo}}</td>
				<td>{{ficha_clinica_list.enfermadades}}</td>
				<td>{{ficha_clinica_list.tratamiento}}</td>
				<td>{{ficha_clinica_list.fecha_enfermedad}}</td>
				<td>{{ficha_clinica_list.fecha_termino_tratamiento}}</td>
				<td>{{ficha_clinica_list.resultado_tratamiento}}</td>
        <td style="border :1px solid transparent ">
				<a class="btn btn-primary" href="{% url 'fichaClinica:ficha_clinica_editar' ficha_clinica_list.id %}"><i class="ion-edit"></i> Editar</a>
              	<a class="btn btn-danger" href="{% url 'fichaClinica:ficha_clinica_eliminar' ficha_clinica_list.id %}"> <i class="ion-android-delete"></i> Eliminar</a>
        </td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% else %}
	<h1>No hay fichas de pacientes</h1>
	<hr>
	<td>
		<a class="btn btn-primary" href="{% url 'fichaClinica:ficha_clinica_crear' %}"> <i class="ion-plus-round"></i> Agregar Ficha Clinica </a>
	</td>
	{% endif %}
</div>
</div>
 </html>
{% endblock %}

fichaClinica/templates/ficha_clinica_update.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Sistema | PACIENTE-Editar</title>
  </head>
{% extends 'adminlte/base.html'%}
{%block content%}
  <div class="row">
      <div class="col-xs-5">
          <h1>EDITAR PACIENTE</h1>
          <hr>
          <form method="POST" action="">
              {% csrf_token%}
              {{form.as_p}}
              <hr>
              <input type='submit' class="btn btn-primary" value='Guardar Cambios'>
            </form>
      </div>
  </div>
  <br>
</html>
{%endblock%}

pacientes/templates/paciente_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sistema | Pacientes</title>
</head>
<body>
    {% extends 'adminlte/base.html'%}

    {%block content%}
    <div class="col-sm-12">
        <h1>Pacientes</h1>
        <hr>
        <form method="POST" action="">
            {% csrf_token%}
            {{form.as_p}}
            <input type='submit' class="btn btn-primary" value='Guardar Registro'>
        </form>
    </div>
</body>
</html>
{%endblock%}

pacientes/templates/paciente_delete.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Sistema | Eliminar Paciente</title>
  </head>
{% extends 'adminlte/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar el paciente "{{paciente_list.id}}" ?</h3>
    <button class = "btn btn-danger" type="submit">Si, eliminar</button>
    <a class = "btn btn-default" href="{% url 'paciente:paciente_listar' %}">Cancelar</a>

</form>
</html>
{% endblock %}

pacientes/templates/paciente_list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema | Listar Pacientes</title>
</head>
{% extends 'adminlte/base.html' %}
{% block content %}
<div id="" class="gray-bg"><br>
	{% if object_list %}
	<div class="table-responsive"/>
	<h1>LISTA DE PACIENTES</h1>
	<hr>
	<table class="table table-bordered">
		<thead>
			<tr>
				<td>Codigo</td>
				<td>Nombre</td>
				<td>Rut</td>
				<td>Fecha de nacimiento</td>
				<td>Fecha ingreso</td>
				<td>Ficha clinica</td>
			</tr>
		</thead>
		<tbody>
			{% for paciente_list in object_list %}
			<tr>
				<td>{{paciente_list.codigo}}</td>
				<td>{{paciente_list.nombre}}</td>
				<td>{{paciente_list.rut}}</td>
				<td>{{paciente_list.fecha_nacimiento}}</td>
				<td>{{paciente_list.fecha_ingreso}}</td>
				<td>{{paciente_list.ficha_clinica}}</td>
        <td style="border :1px solid transparent ">
				<a class="btn btn-primary" href="{% url 'paciente:paciente_editar' paciente_list.id %}"><i class="ion-edit"></i> Editar</a>
              	<a class="btn btn-danger" href="{% url 'paciente:paciente_eliminar' paciente_list.id %}"> <i class="ion-android-delete"></i> Eliminar</a>
        </td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% else %}
	<h1>No hay registro de pacientes</h1>
	<hr>
	<td>
		<a class="btn btn-primary" href="{% url 'paciente:paciente_crear' %}"> <i class="ion-plus-round"></i> Agregar Paciente </a>
	</td>
	{% endif %}
</div>
</div>
 </html>
{% endblock %}

pacientes/templates/paciente_update.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Sistema | PACIENTE-Editar</title>
  </head>
{% extends 'adminlte/base.html'%}
{%block content%}
  <div class="row">
      <div class="col-xs-5">
          <h1>EDITAR PACIENTE</h1>
          <hr>
          <form method="POST" action="">
              {% csrf_token%}
              {{form.as_p}}
              <hr>
              <input type='submit' class="btn btn-primary" value='Guardar Cambios'>
            </form>
      </div>
  </div>
  <br>
</html>
{%endblock%}

templates/adminlte/base.html
{% load static %}<!DOCTYPE html>
<html>
<head>
    {% block title_outer %}
        <title>{% block title %}{{ site.name }}{% endblock %}</title>
    {% endblock %}

    {% block meta %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    {% endblock %}

    {% block stylesheets %}
        {% include 'adminlte/lib/_styles.html' %}
    {% endblock %}

    {% block extra_head %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini {% block body_class %}{% block bodyclass %}{% endblock %}{% endblock %}">

{% block body %}
    <div class="wrapper">
        {% block nav_header %}
            {% include 'adminlte/lib/_main_header.html' %}
        {% endblock %}

        {% block nav_sidebar %}
            {% include 'adminlte/lib/_main_sidebar.html' %}
        {% endblock %}

        {% block content_wrapper %}
        <div class="content-wrapper">
            {% block content_header %}
                <section class="content-header">
                    {% block no_heading %}
                        <h1>
                            {% block page_name %}{% endblock %}
                            <div class="header-actions">
                                {% block page_actions %}{% endblock %}
                            </div>
                            {% block no_description %}
                            <small>{% block page_description %}{% endblock %}</small>
                            {% endblock %}
                        </h1>
                        {% block breadcrumbs %}
                            {# Breadcrumb implementation left to developers #}
                        {% endblock %}
                    {% endblock no_heading %}
                </section>
            {% endblock %}

            {% block content_outer %}
            <section class="content">
                {% block messages %}
                    {% include 'adminlte/lib/_messages.html' %}
                {% endblock %}

                {% block content_block_wrap %}
                    {% block content %}{% endblock %}
                {% endblock %}
            </section>
            {% endblock %}

        </div>
        {% endblock content_wrapper %}

        {% block nav_footer %}
            {% include 'adminlte/lib/_main_footer.html' %}
        {% endblock %}

    </div>
{% endblock body %}

{% block javascript %}
{% include 'adminlte/lib/_scripts.html' %}
{% endblock %}

{% block extra_foot %}{% endblock %}
</body>
</html>

templates/adminlte/components/info_box.html
{% load humanize %}
<div class="info-box bg-{{ color }}">
    {% if not hide_icon %}
        <span class="info-box-icon"><i class="fa fa-{{ icon }}"></i></span>
    {% endif %}
    <div class="info-box-content">
        <span class="info-box-text">{{ header }}</span>
        <span class="info-box-number">{{ number }} {{ unit }}</span>
        {% if percent %}
            <div class="progress">
                <div class="progress-bar" style="width: {{ percent }}%"></div>
            </div>
            {% if how_long %}
                <span class="progress-description">
                    {{ percent }}% Increase in {{ how_long }}
                </span>
            {% endif %}
        {% endif %}
    </div><!-- /.info-box-content -->
</div><!-- /.info-box -->

templates/adminlte/example.html
{% extends 'adminlte/base.html' %}

{% block content %}
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Title</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                    <i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip"
                        title="Remove">
                    <i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class="box-body">
            Start creating your amazing application!
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            Footer
        </div>
        <!-- /.box-footer-->
    </div>
    <!-- /.box -->
{% endblock %}

templates/adminlte/index.html
{% extends 'adminlte/base.html' %}

{% block content %}

{% endblock %}

templates/adminlte/lib/_main_footer.html
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        {% block footer_right %}
            <b>Version</b> {% block version %}0.1{% endblock %}
        {% endblock %}
    </div>

    {% block footer_left %}
    {% block legal %}
    <strong>Copyright &copy; {% now "Y" %}{% if not site %}.{% endif %}
        {% if site %}
            <a href="http://{{ site.domain }}">{{ site.name }}</a>
        {% endif %}
    </strong> All rights
    reserved.
    {% endblock %}
    {% endblock %}
</footer>

templates/adminlte/lib/_main_header.html
{% load adminlte_helpers i18n %}
<header class="main-header">
    <!-- Logo -->
    {% block logo %}
    <a href="{% block logo_href %}/{% endblock %}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">{% block logo_text_small %}<b>A</b>LTE{% endblock %}</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">{% block logo_text %}<b>Admin</b>LTE{% endblock %}</span>
    </a>
    {% endblock %}

    <!-- Header Navbar: style can be found in header.less -->
    {% block nav_bar %}
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        {% block nav_bar_center %}{% endblock %}

        {% block nav_custom_menu %}
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                {% block header_dropdowns %}
                    {% if request.user.is_authenticated %}
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{% avatar_url size=50 %}" class="user-image" alt="User Image">
                                <span class="hidden-xs">{% firstof request.user.get_short_name request.user.get_username %}</span>
                            </a>
                            <ul class="dropdown-menu">
                                {% block user_header %}
                                <li class="user-header">
                                    <img src="{% avatar_url size=180 %}" class="img-circle" alt="User Image">
                                    <p>
                                        {% firstof request.user.get_short_name request.user.get_username %}
                                        <small>Member since {{ request.user.date_joined }}</small>
                                    </p>
                                </li>
                                {% endblock %}

                                <!-- Menu Footer-->
                                {% block menu_footer %}
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="{% block change_password_url %}{% url 'admin:password_change' %}{% endblock %}"
                                           class="btn btn-default btn-flat">{% trans 'Change password' %}</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{% block logout_url %}{% logout_url %}{% endblock %}" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                                {% endblock %}

                            </ul>
                        </li>
                    {% endif %}
                {% endblock header_dropdowns %}
            </ul>
        </div>
        {% endblock nav_custom_menu %}
    </nav>
    {% endblock %}
</header>

templates/adminlte/lib/_main_sidebar.html
{% load adminlte_helpers %}
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        {% block user_panel %}
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{% avatar_url size=90 %}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{% firstof request.user.get_full_name request.user.username %}</p>
            </div>
        </div>
        {% endblock %}

        {% block form %}{% endblock %}

        <!-- sidebar menu: : style can be found in sidebar.less -->
        {% block nav_links_ul %}
        <ul class="sidebar-menu">
            {% block nav_links_outer %}
            <li class="header">{% block nav_heading %}MAIN NAVIGATION{% endblock %}</li>

            {% block nav_links %}
                <li>
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Example link</span>
                    </a>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-money"></i> <span>Contabilidad</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="/contabilidad/traspaso/listar">
                                <i class="fa fa-exchange"></i> Traspaso de fondos
                            </a>
                        </li>
                    </ul>
                </li>
            {% endblock nav_links %}
            {% endblock nav_links_outer %}
        </ul>
        {% endblock nav_links_ul %}
    </section>
    <!-- /.sidebar -->
</aside>

templates/adminlte/lib/_messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% else %}
        <div class="alert alert-info alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% endif %}
    {% endfor %}
{% endif %}

templates/adminlte/lib/_pagination.html
{% if pager and ROOT_MENU.current_menu.view_name %}
    <ul class="pagination pagination-sm no-margin pull-right">
        <li><a href="{% url ROOT_MENU.current_menu.view_name %}?page=1&{{ pager.url_params }}">&laquo;</a></li>
        {% if pager.page > 2 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-2}}&{{ pager.url_params }}">
                    {{ pager.page | add:-2 }}
                </a>
            </li>
        {% endif %}
        {% if pager.page > 1 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-1}}&{{ pager.url_params }}">
                    {{ pager.page | add:-1 }}
                </a>
            </li>
        {% endif %}
        <li class="active"><a href="#">{{ pager.page }}</a></li>
        {% if pager.has_next %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:1}}&{{ pager.url_params }}">
                    {{ pager.page | add:1 }}
                </a>
            </li>
        {% endif %}
        {% if pager.has_next_two %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:2}}&{{ pager.url_params }}">
                    {{ pager.page | add:2 }}
                </a>
            </li>
        {% endif %}
        <li>
            <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.last_page}}&{{ pager.url_params }}">
            &raquo;
            </a>
        </li>
    </ul>
{% endif %}

templates/adminlte/lib/_scripts.html
{% load static %}

{% block scripts %}
<script src="{% static "jquery/dist/jquery.min.js" %}"></script>
<script src="{% static "jquery/dist/jquery-ui.min.js" %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<script src="{% static "bootstrap/dist/js/bootstrap.min.js" %} "></script>
<script src="{% static "admin-lte/dist/js/app.min.js" %}"></script>
{% endblock %}

templates/adminlte/lib/_styles.html
{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static "bootstrap/dist/css/bootstrap.min.css" %}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" type="text/css" href="{% static "admin-lte/dist/css/AdminLTE.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "admin-lte/dist/css/skins/_all-skins.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "icheck/skins/square/blue.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "conflicts/conflicts.css" %}">
{% endblock %}

templates/adminlte/pages/index.html
{% extends 'adminlte/base.html' %}

{% block content %}
    <div class="box">
        <div class="box-body">
            <table class="table table-bordered">
                <tr>
                    <th>#</th>
                    <th>页面URL</th>
                    <th>操作</th>
                </tr>
                {% for page in pager.items %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a target="_blank" href="{% url 'adminlte.example.pages' page_id=page.id %}">{{ page.title }}</a></td>
                        <td><a href="{% url 'adminlte.example.page.edit' page_id=page.id %}">编辑</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix">
            {% include 'adminlte/lib/_pagination.html' %}
        </div>
    </div>
{% endblock %}

templates/prueba.html
{% extends 'adminlte/base.html' %}

{% block title %}My App{% endblock %}
{% block content %}
    Just some example content
{% endblock %}